name = "website"
main = "index.js"
compatibility_date = "2025-02-14"

vars = { AEM_HOSTNAME = "main--author-kit--aemsites.aem.live" }

[env.dev]
vars = { ENVIRONMENT = "dev", AEM_HOSTNAME = "main--author-kit--aemsites.aem.live" }
